### ISSUE TITLE
Weapon API Overhaul: Attributes

### ISSUE THREAD

**Issue by GotoLink** [Mine-and-blade-admin/Battlegear2#114]
Replacing IExtendedReachWeapon, IHitTimeModifier, IPenetrateWeapon with corresponding RangedAttribute (currently defined in ItemWeapon), to be moved in the API.

-Make stuff accessible to custom map makers/server op through /give command (need docs about UUID)
-Enable other mods to manipulate those effects without implementing interfaces (easier support ?)

**Comment by GotoLink** [comment]
Attributes registered since 1.0.8.0.

**Comment by smallcuber** [comment]
I was trying to add the Extended Reach attribute by using command block to my sword in minecraft. However, it seems like after I added the attribute to the sword, the sword didn't actually extended its reach. 
Here is my code:
/give @p 276 1 0 {AttributeModifiers:[{Operation:0,UUIDLeast:4,UUIDMost:4,Amount:10,AttributeName:weapon.extendedReach,Name:weapon.extendedReach}],display:{Name:"Test"}}

**Comment by GotoLink** [comment]
Only weapon.mountedBonus is expected to work.
All others are still non-functional.

**Comment by GotoLink** [comment]
Done.
