### ISSUE TITLE
IOffhandDual#offhandClickAir only fires on client?

### ISSUE THREAD

**Issue by coolAlias** [Mine-and-blade-admin/Battlegear2#116]
According to my tests, IOffhandDual#offhandClickAir only fires on the client side, yet PlayerInteractEvent fires on both sides for RIGHT_CLICK_AIR, which is what I expected from offhandClickAir as well; if this is intentional, it may be a good idea to put a note in the documentation.

Of course, there is always the possibility that I'm doing something completely wrong ;)

For reference, here is the code I used to test, and I was trying to spawn an entity on right click:
@Method(modid="battlegear2")
@Override
public boolean offhandClickAir(PlayerInteractEvent event, ItemStack main, ItemStack offhand) {
	LogHelper.info("Clicking air with offhand; is client? " + event.entity.worldObj.isRemote);
	onItemRightClick(offhand, event.entity.worldObj, event.entityPlayer);
	return true;
}

**Comment by GotoLink** [comment]
Version 1.0.8.0 should have this fixed.
Any old API implementation should be compatible, too.

**Comment by GotoLink** [comment]
Master branch ready.
