### ISSUE TITLE
Needs mod compatibility with Deathchest based mods

### ISSUE THREAD

**Issue by Ninjabee-Redtricity** [Mine-and-blade-admin/Battlegear2#142]
This isn't much a bug or anything but when im playing with other mods that add a deathchest system items in the battlegear duel wield inventory sometimes get destroyed here is a list of mods that need compatibility

Whicthery graves:http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445248-witchery-0-21-0
Ganys Nether Undertaker:http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291095-ganys-nether-miscellaneous-nether-themed-additions

**Comment by TwentyOneZ** [comment]
Use Guardian Chests. It is a deathchest mod that does support Battlegear2.
