### ISSUE TITLE
Mine & Blade Battle Gear 2-Unknown Incompatibility

### ISSUE THREAD

**Issue by DeVipressZephoria** [Mine-and-blade-admin/Battlegear2#147]
It worked before I installed a bunch of mods. Now it loads but I am unable to click R, or I. You can see the 6 extra slots, 3 on right, 3 on left, but when you press R, nothing happens. Also, I have not been able to use the X-Ray mod because that mod also uses R. I do not care about X-Ray mod as much, but you might want to inform others. Most importantly though, it must be incompatible with one of the mods I have downloaded and I have so many that I have no idea which one. Attached is a view of the mods I have downloaded. Are any of these mods unstable with Battle Gear or By themselves? Please help because I really like your mod.
![mods](https://cloud.githubusercontent.com/assets/10429240/5640145/65d4880c-95e7-11e4-879d-ee33c987eb71.jpg)

**Comment by GotoLink** [comment]
The "Draw Weapons" key can be changed in the controls menu.
I don't see any previously reported incompatibility in your list.
Though X-ray mods are extremely suspicious and you shouldn't use those for your own safety.
