### ISSUE TITLE
Client disconnects from server with "Internal server error"

### ISSUE THREAD

**Issue by AnonymousPuppy** [Mine-and-blade-admin/Battlegear2#151]
I'm using a custom modpack, forge .1240, and M&B Battlegear 2 version 1.0.6.3. Anytime somebody on my server dual wields and hits the ground with their left hand, they get disconnected with: "Internal server error". This only happens when right-clicking the ground with the left hand, having a weapon equipped has the same result. The client log doesn't show anything besides disconnecting, but the server log does show something.

Here is what it says: http://pastebin.com/kssWf0cH

Please look into this as soon as possible, I can provide any additional information if necessary. Thank you

**Comment by GotoLink** [comment]
Probably related to #149 
Do you have some version of MCPC/Cauldron installed ?

**Comment by AnonymousPuppy** [comment]
Yes, my server is running "cauldron-1.7.10-1.1240.06.213-server.jar". That's the last version that exists, but sadly I need it for plugins and such. Do you think Cauldron is the issue?

**Comment by GotoLink** [comment]
There was an old conflict with MCPC in that part of the code, which is marked resolved.
Since Cauldron is its continuation project,It is likely a conflict too.
Sadly impossible to fix because Cauldron can't be distributed, and thus tested, or its code read.

**Comment by AnonymousPuppy** [comment]
People are still using it, so I'd really love to have dual wielding work again. I could link the build I'm using, if you want.

**Comment by LemADEC** [comment]
Need help to get those Cauldron binaries to debug it?

**Comment by LegendaryAdmin** [comment]
I could use them! I could also use v. 213 as I am currently on 212. It would be amazing if you could share <3

**Comment by LemADEC** [comment]
I've the 212 one, it's fairly easy to get.

**Comment by LegendaryAdmin** [comment]
I don't want to hijack this ticket but I have massive world save issues with 212 and all previous versions as well. Take a look at this: http://timings.aikar.co/?url=9819258 

Thats 5 minutes on the server with a fresh world, without travel. (Server is in beta and is our pet project)

I am hoping to get the source code for cauldron and talk to some of my devs to see what we can do. If anyone wants to help me figure that out in their spare time, that would be amazing because we are plugin guys and modding is a new beast for us... 

Please contact us at mc.l3gendarypvp@gmail.com

**Comment by LemADEC** [comment]
Did you check your harddrive recently, might be just dying HW here?

**Comment by LegendaryAdmin** [comment]
HDs are fine, We run two other servers and they are not at all effected by this issue

**Comment by rob5251** [comment]
Only seems to occur when players right hand is empty. Right-clicking the ground will cause the internal server error (no matter what item is in the left hand, as long as right hand is empty).
-----
@LegendaryAdmin 
You might be better off getting ready for Sponge, Cauldron is dead now and the devs all moved over to the Sponge project. https://www.spongepowered.org/

**Comment by maniak89** [comment]
fix it by edit NetHandlerPlayServer.java.patch : 36 replace
if (!ItemStack.areItemStacksEqual(this.playerEntity.inventory.getCurrentItem(), p_147346_1_.func_149574_g()))

by
-             if (!ItemStack.areItemStacksEqual(this.playerEntity.inventory.getCurrentItem(), p_147346_1_.func_149574_g()))
+             if (slot != null && this.playerEntity.openContainer != null && !ItemStack.areItemStacksEqual(this.playerEntity.inventory.getCurrentItem(), p_147346_1_.func_149574_g()))

**Comment by GotoLink** [comment]
@maniak89 
See line L34 of the patch.

**Comment by maniak89** [comment]
We don't know another mods installed on the server. This fix is work for my server

**Comment by keenerb** [comment]
Gotolink, I don't really know java, but line 34 is checking if(slot==null), and maniak89's patch is checking if (slot != null.

**Comment by GotoLink** [comment]
AS code, [if(slot==null ...//do nothing or if(slot!=null ...//do thing] is the same process.
Anyways, this is not going to be fixed until the Cauldron patch on this method is accessible somehow.
Which may mean never.
Obviously support for Sponge will be addressed if it reach a release state.

**Comment by LemADEC** [comment]
Sponge is already available for compilation

**Comment by Myrninvollo** [comment]
Hi gottolink  here`s where Kcauldron - https://gitlab.prok.pw/Prototik/KCauldron - KCauldron - continuation of Cauldron minecraft server.

**Comment by GotoLink** [comment]
@Myrninvollo 
Your link is broken on my side.

**Comment by keenerb** [comment]
kCauldron's web page has been down for some days.  Kinda makes me nervous...

**Comment by LemADEC** [comment]
Use this instead: http://tcpr.ca/kcauldron

**Comment by Myrninvollo** [comment]
update: due to the other site still not being up heres a link to the caludron with forge 1388 (1.7.10) https://github.com/gamerforEA/Cauldron-Reloaded_CLOSED  all so the same cauldron version im been modyifing for our Midgard Prodject (https://github.com/Myrninvollo/Midgard-Server) which ive not updated with my RPG changes as of this post.

 im assumeing your still running on forge 1.7.10-10.13.2.1230 as your readme states

hope this helps you sovle the cauldron related issues , if it does and there are cauldron side of things either fork the orignal or you can notify me on twitter @MyrninvolloMC and il add them to my repo as i use Battlegear2 as 1 of our main plugins 
.
yours

Myrinivollo

**Comment by GotoLink** [comment]
@Myrninvollo 
So i guess you have the same NPE on all those unofficial versions of Cauldron ?
I read your repo and got [this](https://github.com/Myrninvollo/Midgard-Server/blob/master/patches/net/minecraft/network/NetHandlerPlayServer.java.patch#L535) which is actually different from the original MCPC patch that Cauldron should be based on (does not include the null check colliding with our own, that MCPC had).
So we'll have to make a special case for Cauldron [here](https://github.com/Mine-and-blade-admin/Battlegear2/blob/1.7.10/battlegear%20mod%20src/minecraft/mods/battlegear2/coremod/transformers/NetServerHandlerTransformer.java#L102)

I will make a test build so you guys can check for each of your Cauldron fork.

**Comment by keenerb** [comment]
I've had this error with M&B since I started using it, back in 1.0.6.3 or thereabouts, with many versions of cauldron.

I'll be more than happy to test out that fixed build.

**Comment by Myrninvollo** [comment]
Thank u gotolink, gamersea fork was the last version before blood started the, bps patches for cauldron. And keenerb yes that is latest version of kcauldron, but it can't be complied becouse both bukkit and firge submodules point to the kcauldron website with us still down. ;(  but thank u for the link :)

**Comment by GotoLink** [comment]
[Test](http://www.mediafire.com/download/xd79nytmwwmxt63/1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar)
I took a look at the kCauldron source, and the MCPC patch is included as we expected. So this Cauldron fork should be compatible already !?
But sadly this means that we have multiple Cauldron versions with maybe different behavior on that specific part of the code. Quite problematic.
Wasn't there a DMCA takedown on Cauldron anyways ? Are all those forks still active ?

**Comment by Myrninvollo** [comment]
Kcauldron is the main fork. My fork will be updated to kcauldron when kcauldron site is back up. But for now I'm going to have to slowly go though the other kcauldron comments and up date my fork manulsy.asvsoon as I got a one sleep, 3am in uk,  il test your fixes out, again thank u for doing this gotolink u are a awsome dev :)

**Comment by keenerb** [comment]
This appears to have fixed the problem for me, but apparantly I'm running an ancient build (forge 1370) of Cauldron; looking to update now.

**Comment by keenerb** [comment]
OK I updated to latest KCauldron and tried it again.  Looks good.

I tried both right- and left-clicking the ground, chests, and doors while holding a weapon and a non-weapon object in both my right hand, left hand, and with empty hands.

Nothing crashed.

**Comment by Myrninvollo** [comment]
Ok can confirm works for my fork, works on kcauldron and works on other versions/forks at tcpr.ca,  so should work for any other private fork of cauldron.  thank u again gotolink :)

**Comment by GotoLink** [comment]
1.0.81 official has been released and include the fix. Closing.

**Comment by keenerb** [comment]
Actually, it's still happening with 1.0.8.1 if you right-click on an entity.  It works on chests and whatnot.

**Comment by GotoLink** [comment]
And you didn't report that before because ...?
Anyway, i'd like to see your new report for this.
This fix can not simply stop working on entities. That is impossible.

**Comment by keenerb** [comment]
Because I just noticed you crash when right-clicking another player.

**Comment by keenerb** [comment]
Yeah, the error message is pretty bizarre actually.

http://pastie.org/10395814

It looks like it might actually be an IC2 classic conflict?  There was no chainsaw involved at all, just right-clicking holding two iron swords...

**Comment by GotoLink** [comment]
Yep, really common conflict. Nothing to do with the above issue, and IC2 specific on top of that.
