### ISSUE TITLE
Rendering error with bspkrsCore Main menu mob rendering

### ISSUE THREAD

**Issue by AnonymousPuppy** [Mine-and-blade-admin/Battlegear2#152]
I'm using a custom modpack, forge .1240, and M&B Battlegear 2 version 1.0.6.3. I am also bspkrsCore, which adds a main menu mob rendering feature. A random entity renders on the left, while the player's character renders on the right.

This is how is normally appears: http://i.imgur.com/qgtiYY9.png

On rare occasions, it decides to pick a mob from this mod, and the main menu screen goes all black. The console is spammed with a several rendering errors every second, and the game is unplayable unless restarted.

Here is the error the console shows: http://pastebin.com/kfwDVhxa

It just keeps going on and on, spamming the console. This is a somewhat rare issue, but I'd appreciate it if you could take a look. I can provide any additional information if necessary. Thank you

**Comment by GotoLink** [comment]
Another mod that tries to render a skeleton with a bow in horrible half-valid state.
Guess we'll have to handle the crash silently.
