### ISSUE TITLE
This mod is crashing with the InfiniteInvo mod

### ISSUE THREAD

**Issue by crunkazcanbe** [Mine-and-blade-admin/Battlegear2#155]
As the title says !

The owner of InfiniteInvo said you could add a tab button for a sub screen in order to make the mods compatible . Don't know what that means , but you probably do . His Github is here
https://github.com/Funwayguy/InfiniteInvo/issues/10

You can see this issue I posted with him , and see what  he said .

Crash is here http://pastebin.com/unkhgs0j

Thanx 

-CrunK

**Comment by GotoLink** [comment]
I know what it means, and that is impossible.
Our mods design are simply incompatible with each other.
