### ISSUE TITLE
Incompatibility with Ender IO's electromagnet

### ISSUE THREAD

**Issue by HenryLoenwind** [Mine-and-blade-admin/Battlegear2#156]
https://github.com/CrazyPants/EnderIO/issues/1760

in short: Battlegear2 installed + magnet activated => (a) right click animations (bows, eating, ...) reset randomly, (b) slot selection (both number keys and mouse wheel) reverts randomly

**Comment by GotoLink** [comment]
Another user of InventoryPlayer#markDirty()...
https://github.com/CrazyPants/EnderIO/blob/master/src/main/java/crazypants/enderio/item/MagnetController.java#L28
It was pretty clear in the javadoc that it is for TileEntity.
Guess we'll have to cover it.

**Comment by coolAlias** [comment]
@GotoLink While the JavaDocs do state the specific use it has for Tile Entities, markDirty() is part of the interface and actually used by other inventories as well. For InventoryPlayer, it sets hasChanged to true, though I haven't searched out specifically what that is for.

Anyway, point being that I don't think it is wrong of people to be using markDirty() in their own implementations especially, and if calling markDirty on the player inventory is consistently causing problems with BG2, perhaps there is something that can be done within BG2 code to not be affected by that?

I'm sure you have done your research, but you know, just a thought. ;)

**Comment by HenryLoenwind** [comment]
@GotoLink I compiled a version with above change and it seems to fix the problem fine. One oddity I noticed is that you cannot use the magnet to break blocks, as the breaking is interrupted all the time. But I did not have time to restest that without BattleGear. I'll do so tonight.

**Comment by GotoLink** [comment]
@coolAlias 
The implementation in InventoryPlayer does nothing. It sets a flag 'inventoryChanged' that only resets back when a new inventory is created (which is, when the player is cloned/reloaded/dead). That also, is clear from the Javadoc. And is accurate from our own research, too.
The current BG2 official build introduce a use for that method, actually pushing the battle inventory to the client. Which is what you would expect based on the method name.
Hoping people would use it with care to better support our inventory.
Calling that method every tick...is not what we'd expected.

@HenryLoenwind 
My fix removes the entire BG2#markDirty() feature. If the magnet can't break blocks, it is probably unrelated with this issue.

**Comment by HenryLoenwind** [comment]
I can confirm that the magnet's left-clickedy reseting is unrelated to BettleGear.

Thanks.
