### ISSUE TITLE
Suggestion to reduce network traffic

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [Mine-and-blade-admin/Battlegear2#157]
As far as I know BattleGear is using a synchronous method to send players' battle equipment between eachother (if I am right this happens every second). I have suggestion about how to turn this process asynchronous quite simply. My solution is not necessarily better (I mean I understand if you don't like the style of the code), but I think it would still worth it to take a look at, because the network traffic generated by the mod itself could be reduced quite considerably.

I have implemented something like I am talking about in my fork project (I use it to decide when my custom attributes should be recalculted due to equipment changes), so the method in a nuthsell:
In the ClientEvents file I have a method (updateEquipment) subscribted to the LivingUpdateEvent. In this method I check for battle equipment changes (by comparing saved itemStacks from the last check to the current itemStacks with ItemStackEquals method) on the client player. Every time a change has been found the client just sends a packet to the server that there was a change.

(You can take a look at what I am talking about:D if you are interested at: https://github.com/ZsoltMolnarrr/BGBattleClasses/blob/master/battlegear%20mod%20src/minecraft/mods/battleclasses/client/BattleClassesClientEvents.java (In my fork project there is only weapon set for the player so the method might be a different than BattleGear needs))

**Comment by GotoLink** [comment]
I am afraid not, it should be the server that has the final say in the equipment change routine. There is too many room for duplicating bugs/hacks with your method.
The "every x second" sync is only a force push from server to tracking clients, for display purposes, which got a configuration option in the latest version anyway. The inventory changes were always covered as required.

**Comment by ZsoltMolnarrr** [comment]
I don't really see how this could cause problems you mention, but I guess this is just because I don't entirely understand how Battlegear operates. Anyway just wanted to help:) You can close the issue
