### ISSUE TITLE
Battlegear 2 + Tinker's Construct + CustomNPC's=Crash/not working

### ISSUE THREAD

**Issue by 05192000** [Mine-and-blade-admin/Battlegear2#163]
Please fix this problem? It seems as if there is a ton of problems with this mod working with others.

**Comment by GotoLink** [comment]
Explain more.

**Comment by 05192000** [comment]
"Noo please don't contact the author, its just that the Quests and Factions tabs conflicts with TiC and.. I forgot what other mod tabs. (In the inventory)"
