### ISSUE TITLE
Change to slots Not Working

### ISSUE THREAD

**Issue by Blitzear** [Mine-and-blade-admin/Battlegear2#169]
![2015-03-10_22 00 31](https://cloud.githubusercontent.com/assets/11407512/6575287/bd7301ea-c6ea-11e4-8763-76d9c6b788fb.png)
![2015-03-10_22 01 27](https://cloud.githubusercontent.com/assets/11407512/6575289/bdfe8a4e-c6ea-11e4-87e9-c09dddd84850.png)

When i'm after install Mine and Blade Battlegear 2, i can't Scroll/change to the item. Can you help me? I'm using Battlegear 2 v1.0.7.0 and using Minecraft Forge 1.7.10

**Comment by Drehverschluss** [comment]
Press "R"

**Comment by ZsoltMolnarrr** [comment]
This is the most detailed issue I have seen for a while:D
