### ISSUE TITLE
There is something wrong when it is used in server.

### ISSUE THREAD

**Issue by 5igm** [Mine-and-blade-admin/Battlegear2#172]
I found a problem that when players put bow in Battlegear2 position, players can use bow open the chest which is protected by residence. Could you help to fix it? Thank you! Wait for your response.

**Comment by GotoLink** [comment]
What is that "protected by residence" thing ?

**Comment by Time6628** [comment]
Works on GreifPrevention too.

**Comment by GotoLink** [comment]
Added CraftBukkit support. Should have fixed it.
