### ISSUE TITLE
Coss mod crash.

### ISSUE THREAD

**Issue by NJM1564** [Mine-and-blade-admin/Battlegear2#177]
Mine and Blade/ ProjectE
http://pastebin.com/HezNheVx

**Comment by GotoLink** [comment]
From the error report:
You have a ProjectE "Alchemical Bag" in inventory.
And something like "density gem" interacting with it.
AFAIK, some data couldn't be generated from the NBT.
Will try to reproduce this.

**Comment by GotoLink** [comment]
Couldn't find the setup that would cause this.
