### ISSUE TITLE
Duplication Bibliocraft and battlegear

### ISSUE THREAD

**Issue by yerbuky** [Mine-and-blade-admin/Battlegear2#178]
Well. i'm spanish. i'm sorry for my english.
I had a problem 20 min ago in my server mcpc.1.7.2 when i interact with id 191, 188 and i have sword in my right hand, when i click it, i have server error, but when i join into the server. i have 2 sword. one this in my hand and other in the id 191(table)bibliocraft.

El tener una espada en la mano cuando la quieres guardar en la mesa de bibliocraft. el server me da error y cuando vuelvo a entrar, tengo una espada en la mano y otra en la mesa de bibliocraft.

**Comment by yerbuky** [comment]
is ther anyway for disabled penetration?

**Comment by GotoLink** [comment]
You should use Minecraft 1.7.10, and Battlegear 1.0.8.0.
Please report if you still have this same bug.

**Comment by Tennik** [comment]
Can you fix that bug in 1.7.2 version of the mod please?

**Comment by GotoLink** [comment]
Busy with updating for 1.8.
And i have yet to see a crash report on this issue, which would help fixing it.

**Comment by Tennik** [comment]
There it is. But this is not crash. This is Internal server error. For example, I show a issue, which made a player on my server. He duped the swords. 

14:28:10 [WARNING] Failed to handle packet for /91.189.245.147:54239
14:28:10 java.lang.ArrayIndexOutOfBoundsException: 152
14:28:10 	at jds.bibliocraft.blocks.BlockTable.func_149727_a(BlockTable.java:294) ~[BlockTable.class:?]
14:28:10 	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:454) ~[mn.class:?]
14:28:10 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:869) ~[mx.class:?]
14:28:10 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jc.class:?]
14:28:10 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jc.class:?]
14:28:10 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:206) ~[ef.class:?]
14:28:10 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [ms.class:?]
14:28:10 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957) [MinecraftServer.class:?]
14:28:10 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:433) [lj.class:?]
14:28:10 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:774) [MinecraftServer.class:?]
14:28:10 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [MinecraftServer.class:?]
14:28:11 	at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
14:28:11 [INFO] MineProKiller lost connection: Internal server error
14:28:11 [INFO]  --> MineProKiller leaved us :(

**Comment by GotoLink** [comment]
Hoping 1.11 fixed that type of crash.
