### ISSUE TITLE
Problem with dual weapons and Boats

### ISSUE THREAD

**Issue by foxbeta90** [Mine-and-blade-admin/Battlegear2#181]
The standard "vanilla" boat if right clicked when dual wield, cause a bug in single player and multiplayer servers.

Description: The boat disappear like it is broken and after a log off and log in on the server ( in single player -> save and quit to the title and after re opening the world ) the player is actually on the boat.

Sorry for my poor english :V

**Comment by GotoLink** [comment]
Try latest version (1.0.8.0).
Please report even if your issue is fixed, so i can close this.

**Comment by foxbeta90** [comment]
Yes! The update did the magic! Ty for the quick reply.
