### ISSUE TITLE
Dual wielding: not using the offhand weapon

### ISSUE THREAD

**Issue by khardix** [Mine-and-blade-admin/Battlegear2#182]
When I dual wield and try to attack with the off-hand weapon (RMB), I instead end using the main-hand weapon RMB ability (i.e. blocking).

The issue manifest itself in both "vanilla" Mine&Blade (tested on instance with only this mod installed, using vanilla swords) and with other mods, that may alter it (tested on instance with multiple mods, namely Tinker's Construct and Tinker's Defense - in this case the RMB invokes the correct RMB ability of the main hand weapon).

**Comment by GotoLink** [comment]
Are you trying to attack a mob ?
Blocks are no longer "attacked" since version 1.0.8.0, since people would actually think blocks were supposed to break from the offhand. They are not.

**Comment by khardix** [comment]
No, I was swinging to the air, attacking a mob seems to work correctly - both weapons strike them.

> Blocks are no longer "attacked" since version 1.0.8.0, since people would actually think blocks were supposed to break from the offhand. They are not.

I'm not sure I understand "block are not supposed to break form the offhand" - what do you mean by it? (I'm not a native English speaker, so I just may have trouble translating it.)

**Comment by GotoLink** [comment]
Before the change, the player left hand would swing at blocks. The same as the player right hand swing at blocks on left click, which break blocks. So people were assuming...
Anyway, stuff is working as intended.
