### ISSUE TITLE
Dupe of swords

### ISSUE THREAD

**Issue by Tennik** [Mine-and-blade-admin/Battlegear2#187]
Hi! I have a trouble. Players can dupe swords with this mod and with table from Bibliocraft mod.
When player hold 1 weapon in a new slot from Battlegear and click on a table from Bibliocraft mod he will be kicked from a server with "Internal server error". Then player can join the server again and there will be 1 sword on the table and 1 sword in his hand. Now he has 2 swords and he can duplicate it once and once more.
Can you fix that?

**Comment by GotoLink** [comment]
Duplicate of #178, probably.

**Comment by Tennik** [comment]
I cant use 1.7.10 beacause my project is on 1.7.2 version now =(
