### ISSUE TITLE
Crash when equipping items in the sword slot

### ISSUE THREAD

**Issue by devryb** [Mine-and-blade-admin/Battlegear2#191]
If you equip a player focus from AM2 into the sword slot the server will crash with this:

http://pastebin.com/BQREtAH3

Version: 1.0.8.0

**Comment by devryb** [comment]
This actually happens when equipping any item in the sword slot on a server instance.
Also confirmed with forge only if you were wondering ;)
Here's a crash report for that:

http://pastebin.com/nVhrZgXy

**Comment by DrasticDemise** [comment]
The crash occurs when placing non-eligible items in a battle gear slot where as in single player it does not let you, it attempts to let you in multiplayer causing the server to crash.

**Comment by devryb** [comment]
We compiled the latest commit and the issue is still present:

https://gist.github.com/devryb/b0184411bf66f1a73c0c
