### ISSUE TITLE
Duel wielding swords issue

### ISSUE THREAD

**Issue by thedragonlordman** [Mine-and-blade-admin/Battlegear2#192]
Every time I use this mod, there is a weird glitch. Normally, right click is attack(or place something). But when I right click, both swords or battle axes will block. Only left click is attack. I don't know if this is just my computer or the config but I need help.

**Comment by DrZed** [comment]
I'm having this issue as well recently it may be a conflict or it could be a bug with the mod :\ I miss attacking with 2 weapons also it uses the tinkers' right click ability instead of attacking

**Comment by DrZed** [comment]
Downgrading fixed it for me so it's not incompat issue it's a bug

**Comment by DrZed** [comment]
Dual wielding isn't supposed to work anymore?

**Comment by GotoLink** [comment]
Dual wielding is working. Wrong report is wrong.

**Comment by DrZed** [comment]
You're a shitty mod author if you don't even attempt to hear your users out

**Comment by DrZed** [comment]
I meant dual wielding as in attack with both hands...

**Comment by GotoLink** [comment]
You can attack with both hands. Unless the item you hold prefers doing an "use" ability like tinkers', which is a feature that has been requested many times.
Yes blocking is also a feature of the game. Maybe you only played 1.9 snapshots till now, but that doesn't excuse you for being rude.

**Comment by DrZed** [comment]
Well I can't attack with both hands using any vanilla-ish swords from other mods like spectre sword from random things... Do what I do make a config for everything possible... Like removing the right clicking...

**Comment by GotoLink** [comment]
What did you try to attack then ?

**Comment by DrZed** [comment]
Nothing I didn't really try to attack anything I was trying to swing my right sword and it only blocked, as for my tic sword I dual wielded longswords and it only did right click effect... I find it very anoying

**Comment by DrZed** [comment]
It's just a habit of mine to play with my weapons when bored

**Comment by GotoLink** [comment]
So you tried to attack nothing, and nothing was attacked.
This should close the discussion.

**Comment by DrZed** [comment]
That was stupid >_> it didn't swing sword... Unless you made a special handle for that it wouldn't change...

**Comment by GotoLink** [comment]
Wrong report is still wrong.
