### ISSUE TITLE
items disappearing on teleport or disconecting

### ISSUE THREAD

**Issue by Sarcastler** [Mine-and-blade-admin/Battlegear2#193]
Hello. I have a server 1.6.4. all is well. but when I disconnect and reconnect I lose equipped items in the inventory battle ... when I go to the nether same thing happens when I leave the world and return survival disappear ... the log console does not detect anything, but I think it lacks is having an inventory save.
I expect a rapid and accurate response, if possible and thank you for your attention.

**Comment by GotoLink** [comment]
Inventory has always been saved.
Probably something like Cauldron/MCPC+/Bukkit incompatible with Forge installed on your server.
1.6.4 is no longer supported anyway.
