### ISSUE TITLE
Dual-Wield slots not available when TiC armor module is disabled.

### ISSUE THREAD

**Issue by reteo** [Mine-and-blade-admin/Battlegear2#196]
In preparation for removing Tinker's Construct (once I find an alternative for Iguana Tinker's Tweaks), I tried disabling all the modules in TinkersModules.cfg, thereby preventing the crafting of all Tinker's Construct items.  However, upon doing so, once I started the game, I can no longer access the Battlegear armor UI.  The buttons on the left are missing, even though they were enabled in the config.

**Comment by GotoLink** [comment]
Battlegear doesn't support the module individual settings, only entire Tinker's mod being loaded or not.
You'd need to use Battlegear optional keybinds config till more TC support is added to handle your case.

**Comment by reteo** [comment]
On 1.7.10, no further support will be possible; Tinker's Construct will no longer be updated, except for critical bugs.

Still, thanks for responding; I'll go ahead and get the keybinding set up.  Perhaps I'll just ask that there be an option in the config to disable TiC support.

**Comment by GotoLink** [comment]
We don't need any changes from Tinker's. Actually it would be best if they didn't touch a thing and let us take it in our hands.
I'll patch the support in 1.7.10.

**Comment by GotoLink** [comment]
Fixed in 1.0.8.2.
