### ISSUE TITLE
Won't work with Infinite Inventory Mod, already asked other dev to fix, he says he can't do it from his end. So apparently you need to update your mod to fix the compatibility issue.

### ISSUE THREAD

**Issue by MineSlaylehur** [Mine-and-blade-admin/Battlegear2#199]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/26/15 9:48 PM
Description: Unexpected error

java.lang.RuntimeException: Player inventory has been replaced with class infiniteinvo.inventory.BigInventoryPlayer
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:62)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_156_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_71403_a(Unknown Source)
	at com.mrnobody.morecommands.patch.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:76)
	at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
	at com.mumfrey.liteloader.core.event.EventProxy$2.$event00046(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source)
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.battlegear2.BattlemodeHookContainerClass.onEntityJoin(BattlemodeHookContainerClass.java:62)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_156_BattlemodeHookContainerClass_onEntityJoin_EntityJoinWorldEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1334)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:159)
	at net.minecraft.client.Minecraft.func_71353_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_71403_a(Unknown Source)
	at com.mrnobody.morecommands.patch.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:76)
	at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
	at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
	at com.mumfrey.liteloader.core.event.EventProxy$2.$event00046(Unknown Source)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['MineSlaylehur'/527, l='MpServer', x=8.50, y=66.62, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~NULL~~
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3290734152 bytes (3138 MB) / 5248544768 bytes (5005 MB) up to 8160477184 bytes (7782 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 2 loaded mod(s)
          - WorldEditCUI version 1.7.10_00
          - WorldEditWrapper version 1.2.0
	LaunchWrapper: 46 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: pl.asie.lib.core.AsieLibCoremodTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: net.malisis.core.asm.MalisisCoreTransformer
          - Transformer: com.mrnobody.morecommands.asm.transform.TransformBlockRailBase
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.worldeditwrapper.asm.InteractionTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn4096M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1517 Optifine OptiFine_1.7.10_HD_U_C1 73 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1517} [Minecraft Forge] (forge-1.7.10-10.13.4.1517-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.10.5+unknown-b0.git-unknown} [Malisis Core] (Malisis' Core.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles.jar) 
	UCHIJAAAA	surpriseeggs{1.0.6} [Surprise Eggs] (Adventure Backpack.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (Adventure Backpack.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI.jar) 
	UCHIJAAAA	armourersWorkshop{1.7.10-0.33.0.84} [Armourer's Workshop] (Armourer's Workshop.jar) 
	UCHIJAAAA	asielib{0.2.7} [asielib] (asielib.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks.jar) 
	UCHIJAAAA	Railcraft{9.6.1.0} [Railcraft] (Railcraft.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	chisel{2.3.10.37} [Chisel 2] (Chisel 2.jar) 
	UCHIJAAAA	RDMenuServer{2.0.0.2} [RDMenuServer] (CustomMenu.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNpcs.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.2.3} [Damage Indicators] (Damage Indicators.jar) 
	UCHIJAAAA	darkcore{0.3} [Dark Core] (Dark Core.jar) 
	UCHIJAAAA	props{2.0.2} [Decocraft] (Decocraft.jar) 
	UCHIJAAAA	EE3{0.3.507} [Equivalent Exchange 3] (Equivalent Exchange 3.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	FoodPlus{3.2rS} [§bFood Plus] (FoodPlus.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil.jar) 
	UCHIJAAAA	GraviGun{4.0.0-beta} [GraviGun] (GravityGun.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats.jar) 
	UCHIJAAAA	HatStand{4.0.0} [HatStand] (HatStand-4.0.0.jar) 
	UCHIJAAAA	infiniteinvo{1.0.44} [InfiniteInvo] (InfiniteInvo-1.0.44.jar) 
	UCHIJAAAA	InventoryPets{1.1.2a} [Inventory Pets] (Inventory Pets.jar) 
	UCHIJAAAA	IronChest{6.0.60.741} [Iron Chest] (Iron Chest.jar) 
	UCHIJAAAA	pacman{1.0.7} [Killer Pacman] (Killer Pacman.jar) 
	UCHIJAAAA	lucky{5.1.0} [Lucky Block] (LuckyBlock.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.4.3} [Malisis' Doors] (Malisis' Doors.jar) 
	UCHIJAAAA	mcheli{0.10.6} [MC Helicopter] (MC Helicopter.zip) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine & Blade Battlegear 2 - Bullseye.jar) 
	UCHIJAAAA	MobProperties{0.4.0} [Mob Properties] (Mob Properties.jar) 
	UCHIJAAAA	mrnobody_morecommands{1.6} [More Commands] (MoreCommands-1.7.10-1.6.jar) 
	UCHIJAAAA	Morph{0.9.1} [Morph] (Morph.jar) 
	UCHIJAAAA	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfish's Furniture Mod.jar) 
	UCHIJAAAA	MultiPageChest{1.3.2} [Multi Page Chest] (Multi-Page-Chest-Mod-1.7.10.jar) 
	UCHIJAAAA	MutantCreatures{1.4.8} [Mutant Creatures] (Mutant Creatures.jar) 
	UCHIJAAAA	NEIAddons{1.12.10.33} [NEI Addons] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo] (NEI Addons- Ex Nihilo.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis.jar) 
	UCHIJAAAA	origin{3.3.0} [Origin] (Origin.jar) 
	UCHIJAAAA	pandorasbox{2.0.1} [Pandora's Box] (Pandora's Box.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-4} [PortalGun] (PortalGun-4.0.0-beta-4.jar) 
	UCHIJAAAA	AS_Ruins{15.1} [Ruins Spawning System] (Ruins-1.7.10.jar) 
	UCHIJAAAA	SaintsCore{0.8} [Saintscore] (Saintscore.jar) 
	UCHIJAAAA	securitycraft{v1.7.4.1} [SecurityCraft] (SecurityCraft.jar) 
	UCHIJAAAA	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (Soul Shards- The Old Ways.jar) 
	UCHIJAAAA	statues{2.1.3} [Statues] (Statues.jar) 
	UCHIJAAAA	TardisMod{0.99} [Tardis Mod] (Tardis Mod.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (The OreSpawn Mod.zip) 
	UCHIJAAAA	secretroomsmod{4.7.1} [The SecretRoomsMod] (The SecretRoomsMod.jar) 
	UCHIJAAAA	TrailMix{4.0.0} [TrailMix] (TrailMix.jar) 
	UCHIJAAAA	transformers{${version}} [Transformers Mod] (Transformers Mod.jar) 
	UCHIJAAAA	jordy141minecraftmagicwrench{0.5 Alpha} [Magic Wrench] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	uncraftingTable{1.7.10 Alpha 1} [Uncrafting Table] (UncraftingTable-1.7.10-alpha1.jar) 
	UCHIJAAAA	weepingangels{3.3.2} [Weeping Angels] (Weeping Angels.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (Witchery.jar) 
	UCHIJAAAA	Kradxns Minimap{2.0} [Minimap] (Xray2.02.jar) 
	UD	asielibcore{} [AsieLib CoreMod] (minecraft.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GTX 780/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1517-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 780/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.82, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [YoutubersSkin]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: On (16)

**Comment by GotoLink** [comment]
Both mods rely on changing the player inventory for their purpose.
The crash is intended and explain the situation clearly.
Only a "merge mod", including both battlegear and infiniteinvo would solve the issue.
Probably never going to happen.
