### ISSUE TITLE
attack with two swords at the same time.

### ISSUE THREAD

**Issue by ciroreed** [Mine-and-blade-admin/Battlegear2#200]
does it have sense to have two swords if you cannot attack with them? 

> Right click attack with one sword.
> Left click defensive position with the two swords. 

I guess this is a misunderstanding..

I tested the mod yesterday and it looks really awesome. :)

**Comment by GotoLink** [comment]
Push both buttons at the same time ?
You didn't describe your issue very well.

**Comment by ciroreed** [comment]
sry, i ask about how to have two weapons that can attack, If i have two vanilla swords i can only perform an attack with one, regular right click. Left click will stand as a defensive position.. :\

What im doing wrong? 

thanks??

**Comment by ciroreed** [comment]
may i help with mod development?

**Comment by GotoLink** [comment]
In 1.7.10:
Sword blocking is done with "Use Item" keybind on blocks or air.
Mouse over a mob to attack it.
In 1.8:
Sword blocking is disabled, just like "vanilla" 1.9 will.

This project is open, you can submit pull requests.
