### ISSUE TITLE
[1.8] NoSuchFieldError: AXIS during API use

### ISSUE THREAD

**Issue by Spartan322** [Mine-and-blade-admin/Battlegear2#205]
Using the 1.8 release, I have noted a crash problem that has sprung up (on my side at least).
It doesn't appear to be an influence from what I've done (yet).

Log: https://gist.github.com/Spartan322/222fe672d8a2abf4f719

**Comment by Spartan322** [comment]
Ah, crap, sorry, forgot to take into account older forge version, will retry in a newer version.

**Comment by GotoLink** [comment]
AXIS is a Minecraft field from BlockRotatedPillar.
Probably a mapping issue... do you have mapping from mcp 20150401 or later ?

**Comment by Spartan322** [comment]
Yeah, I was pretty sure AXIS was cauing the crash because of me doing something stupid (like forgetting the mapping), and of course the mapping is my issue, thanks.

**Comment by Spartan322** [comment]
A different issue attributed to Minecraft in which IRetextureableModel class doesn't exist,

**Comment by GotoLink** [comment]
IRetextureableModel is a Forge class. I recommend build 1450.

**Comment by Spartan322** [comment]
And git screwed up again, thanks for the help
