### ISSUE TITLE
[1.8] Cannot block while not in battle mode

### ISSUE THREAD

**Issue by coolAlias** [Mine-and-blade-admin/Battlegear2#206]
This is probably intended, but it really messes up the feel of the game, especially with items added by other mods with which one expects to be able to block even when not in battle mode or that do not work properly in battle mode.

If you do want it to work this way, would it be possible to provide a configuration option to allow normal blocking? Yeah yeah, 1.9, I know, but for myself I prefer to cross that bridge when we come to it, rather than early.

**Comment by GotoLink** [comment]
An option is fine, i guess.

**Comment by coolAlias** [comment]
Thanks! That will make it so I can still test items such as my shields as though BG2 isn't installed even when it is, and that's always a plus in my book :+1:

**Comment by xellandres** [comment]
So, how can i disable that and still blocking? or not yet?

**Comment by GotoLink** [comment]
Next version will include a configuration to enable item blocking.

**Comment by xellandres** [comment]
Ohhh ok thank you u are the best :D
