### ISSUE TITLE
[1.8]Issue with Thaumcraft

### ISSUE THREAD

**Issue by xellandres** [Mine-and-blade-admin/Battlegear2#209]
I play with BT2 and Thaumcraft from older versions, and now i play with versions 1.8 but now i cant block or use abilities from thaumcraft on the right click please help me :/

**Comment by GotoLink** [comment]
Please add more details.
What it is the thing you want to do in Thaumcraft that relates to combat ?
How do you normally use it (without Battlegear mod) ?
What happened in older versions that no longer does ?

**Comment by xellandres** [comment]
Ok sorry, in Thaumcraft the weapond have others abilities like the sword have a shield of air with the right click (block click) or normal sword, i cant block with a normal sword.
In older version i had the 2 mods and i have no issues. Thaumcraft and Battlegear was full compatible.

**Comment by coolAlias** [comment]
See issue #206 - this is exactly what I was talking about there.

**Comment by GotoLink** [comment]
Then it is already fixed.

**Comment by xellandres** [comment]
Ok thx
