### ISSUE TITLE
 Chest protection plugin and 1.7.10 battlegear2

### ISSUE THREAD

**Issue by killamuredya** [Mine-and-blade-admin/Battlegear2#210]
hello developer when you have a food in one hand and sword on another you can open a chest in result of this there is no chest related protection plugin that can stop anyone from raiding me or others can you patch this up for us?

**Comment by GotoLink** [comment]
Could be more specific. There are probably billions of "protection" plugins. No way can they all be supported.

**Comment by killamuredya** [comment]
okay i use worldguard and griefprevention i use this bug and i can access somone chest easy and then i look around spigot for another plugin i couldnt find a great one reason being because griefprevention is great for mods and worldguard too basically the well known protection plugin is not stopping this i have tried using a skript plugin and try to patch it up from there and yea there was no way i can patch it because of that offhand this battlegear mod is for crazy craft 3.0 the well known modpack and poeple like me who use your amazing mod in our modpacks on technic profile

**Comment by GotoLink** [comment]
[This anti-grief tool](http://www.curse.com/bukkit-plugins/minecraft/grief-prevention) and [this other anti-grief tool](http://www.curse.com/bukkit-plugins/minecraft/worldguard), you mean ?
Those are open source, so maybe something can be done.

**Comment by killamuredya** [comment]
I would do it but  i don't know how to java code

**Comment by LazerCorn3114** [comment]
Hey i'm having the same issue there is there any compatible fixes?

**Comment by runescapejon** [comment]
This problem doesn't happen on 1.6.4 if this information help in anyway.

**Comment by mnathan12** [comment]
i am having the same issue is this being worked on?

**Comment by mnathan12** [comment]
if its not being worked on what should i do or should i just remove this mod

**Comment by FuckMeHard** [comment]
Please fix this bug for 1.7.10 IM ALSO HAVING THE SAME ISSUE. People can Raid with the Duel glitch in a Claim! Are u already working on the compatibility bug?!

**Comment by GotoLink** [comment]
The issue is being worked on. Compatibility with plugin is tricky because we need to emulate a big chunk of the plugin environment for it to work.

**Comment by runescapejon** [comment]
is this still being work on ? i know its kinda tricky getting to to respect permission region type of plugins

**Comment by GotoLink** [comment]
An attempt at a fix can be downloaded [here](https://github.com/GotoLink/Battlegear2/raw/1.7.10/battlegear%20dist/1.7.10-MB_Battlegear2-Bullseye-1.0.8.4.jar)
Please report if that solves your issue.

**Comment by runescapejon** [comment]
https://www.youtube.com/watch?v=6bza-NixsOY&feature=youtu.be
no that didnt fixed it and it seem when bypasing it show "null" in console i made a video on showing you how to bypassing a chest protection plugin like Griefprevention's 
http://mods.curse.com/bukkit-plugins/minecraft/grief-prevention

**Comment by GotoLink** [comment]
Can you show the log files ?
I updated a small patch to the test version, so i can see better what is happening.

**Comment by runescapejon** [comment]
server log http://pastebin.com/BWG0SLnC
client log http://pastebin.com/Dtkkam6J
Client Fml-client-latest-log http://pastebin.com/wJKFRD6V
fml-server-latest  http://pastebin.com/33ETUqGJ

I hope this is all you need

**Comment by GotoLink** [comment]
fml-server-latest is good enough, thank you.
I am not changing the version number for test versions. I can't guarantee good results with GriefPrevention yet. I don't really have the means to setup a server with your KCauldron version.
Could you update from the previous link ? Thanks again.

**Comment by runescapejon** [comment]
Hmm  what link ? Sorry

**Comment by runescapejon** [comment]
I can give u the links to the kcauldron if you like

**Comment by GotoLink** [comment]
I am talking about the previous link i gave for the test version.
Get the new patch from it and test again, please. It worked on the tests i ran.

**Comment by runescapejon** [comment]
Fml-server-latest log http://pastebin.com/a7iEtmQL
nothing new but shows `org.bukkit.craftbukkit.event.CraftEventFactory` and `null` in console when performing the bypassing glitch with griefpreventions

**Comment by GotoLink** [comment]
Apparently the CraftEventFactory class in your KCauldron version isn't where it is supposed to be.
Just added a fix to cover that.

**Comment by runescapejon** [comment]
still no fixed
http://pastebin.com/PRb0vWp6 - server log
http://pastebin.com/DE9Ae96T  - fml server log

**Comment by runescapejon** [comment]
i use the latest version of kcauldron this is there official download page
https://repo.prok.pw/pw/prok/KCauldron/
and offical site https://gitlab.prok.pw/KCauldron/KCauldron

**Comment by GotoLink** [comment]
Well those are sources i relied on, but are apparently innacurate in real life tests.
Your log report whitespaces in the path name : 'battlegears%20test%20server'
It might be worth testing without those spaces while i find a fix.

**Comment by runescapejon** [comment]
Omg!!! it work!!! i took out the space :dancer:  THANKS you :D

**Comment by runescapejon** [comment]
can you notice me when or fix your fix the space issue
