### ISSUE TITLE
[1.8] Inventory Error (Multiplayer Crash)

### ISSUE THREAD

**Issue by BlackYamato** [Mine-and-blade-admin/Battlegear2#211]
Environment:
・Java 8u66 64bit
・Minecraft 1.8.0
・Minecraft Forge 11.14.4.1563
・Mine & Blade: Battlegear 2 - Bullseye - 1.0.9.0

Client Crash Report:
http://pastebin.com/FVHtUBN3

Data of a player becomes abnormal.
Player of clients who are in the vicinity of this player to crash.

**Comment by GotoLink** [comment]
Same fix as #203
