### ISSUE TITLE
right-click action cancelled for items from Zelda Sword Skills

### ISSUE THREAD

**Issue by Mumberthrax** [Mine-and-blade-admin/Battlegear2#212]
Attempting to use some items with a right-click action from the [zelda sword skills](http://minecraft.curseforge.com/projects/zelda-sword-skills) mod while mine&blade is installed seems to achieve no effect. e.g. hookshot, clawshot, whip. I'm not certain if this is an issue with Battlegear2 or with ZSS.

running mc 1.8; forge 11.14.4.1563; ZSS 3.0.3b; M&B 1.0.9.0

(edit: same results in forge 11.14.3.1450; 11.14.3.1464)

steps to duplicate:

* install both mods.
* create a new creative world
* give yourself the hookshot item, the clawshot, and the whip.
* place a wooden block in the world, such as oak planks or a wood log.
* place a "beam" block from the zelda sword skills mod someplace, several meters up.
* place a stone block somewhere in the world, cobblestone or smoothstone
* put the hookshot, whip, or clawshot in the hotbar, or in the mine&blade offhand inventory slot
* aim the hookshot at the wood, right click and hold.
* aim the clawshot at the stone, right click and hold.
* aim the whip at the beam, right click and hold.

To observe intended effects, remove the Mine & Blade: Battlegear 2 mod from the minecraft instance and repeat the above steps.

Edit: the magic mirror item is also affected, though it does not seem allowed to go into the offhand inventory slot.

**Comment by coolAlias** [comment]
Already fixed. See #206
