### ISSUE TITLE
Dynamic Lights compatibility for torches in left hand

### ISSUE THREAD

**Issue by chrisk123999** [Mine-and-blade-admin/Battlegear2#223]
In more recent version for 1.7.10 the dynamic lights compatibility has only been working when the torch is in the right hand, but not when it's in the left.  Is this intended or a bug?

**Comment by GotoLink** [comment]
Something changed internally from DynamicLights side. Older versions of it should work fine.
It is a minor issue so will be fixed in 1.8.9 or later.

**Comment by GotoLink** [comment]
Added in 1.8.9.
