### ISSUE TITLE
Crash When Blocking With Shield

### ISSUE THREAD

**Issue by Roxololindo** [Mine-and-blade-admin/Battlegear2#226]
Log: [http://pastebin.com/bq1e5LPx](http://pastebin.com/bq1e5LPx)
I've had this occur every time I've blocked with a shield, using both default Battlegear 2 shields and Zelda Sword Skills shields, against both vanilla and modded mobs.

**Comment by GotoLink** [comment]
Apparently related to @Lance5057 TinkersDefense mod.

**Comment by Lance5057** [comment]
This is my fault. Forgot to make sure it was one of my shields before trying to go through the event.

**Comment by GotoLink** [comment]
Assuming fixed. Out of our control anyway.
