### ISSUE TITLE
World not Opening

### ISSUE THREAD

**Issue by NukeDude** [Mine-and-blade-admin/Battlegear2#227]
Whenever I open a world, it just closes it and brings me back to the title screen. I'm not using any other mods. It can't be a memory issue, because It's not using up much of my Minecraft memory at all.

**Comment by meeo125** [comment]
yes thank you I'm having the same problem! problem if you have found a solution please!!! tell me thank you so much!

**Comment by GotoLink** [comment]
Can't reproduce.
Need log.
Grab latest version for 1.8.9.

**Comment by NukeDude** [comment]
I figured it out. My computer just didn't have enough RAM. Works perfectly with my new one.

**Comment by NukeDude** [comment]
I had 4G before, now I have 8G

**Comment by GotoLink** [comment]
Solved then.
