### ISSUE TITLE
Balkon's Weapon Mod Compatability

### ISSUE THREAD

**Issue by ElasticKnife** [Mine-and-blade-admin/Battlegear2#228]
This probably isn't too high of a priority, but trying throw a boomerang from Balkon's Weapons mod out of either dual wield hand (regardless of whether or not anything is in the other hand) crashes the game.  Also when I load back in there is a dupe boomerang as if it was thrown, which I can pick up, but the original item is also still in my hand.  Don't know if this is an issue for any other components of that mod.  Report attached.

[crash-2016-07-07_09.11.45-client.txt](https://github.com/Mine-and-blade-admin/Battlegear2/files/352355/crash-2016-07-07_09.11.45-client.txt)

**Comment by GotoLink** [comment]
On weapon mod side. Can't fix.

**Comment by GotoLink** [comment]
Hoping 1.11 fixed that type of crash.
