### ISSUE TITLE
Reforged Mod Compatibility

### ISSUE THREAD

**Issue by ThexXTURBOXx** [Mine-and-blade-admin/Battlegear2#230]
Hi Mine-and-blade-admin,
Silvercatcher and I made a mod (Reforged), which is basically a complete rewrite of Balkon's Weapon Mod. Nearly everything works fine, but if I want to load a weapon (by right-clicking), then it doesn't work, when your mod is installed. As I noticed, your mod adds new behaviour for those things. Am I able to bypass this behaviour or do you have to edit your mod to do so?

Thanks in advance
-ThexXTURBOXx

**Comment by GotoLink** [comment]
Do you use the EnumAction.BLOCK for your item right click ?
Then Battlegear cancel that by default. Our mod has a configuration value which users can change for compatibility.

If you want custom behavior while dual wielding, this need particular support. See our API package.

**Comment by ThexXTURBOXx** [comment]
Ok, this is the problem.
I use the EnumAction.BLOCK.
Then I need to find another method how I could do this.
Thanks for your help!
 - Nico

**Comment by GotoLink** [comment]
No longer accurate in 1.11.
