### ISSUE TITLE
Crash when using a shield and lycanites creatures attack

### ISSUE THREAD

**Issue by lightning02** [Mine-and-blade-admin/Battlegear2#231]
http://pastebin.com/er8iHMMi
In a private server 1.7.10

**Comment by GotoLink** [comment]
See case #226

**Comment by lightning02** [comment]
@Lance5057 should I expect an update of tinker def, yeah?

**Comment by Lance5057** [comment]
July 30th

**Comment by lightning02** [comment]
Any news reguarding the bugfix update?
