### ISSUE TITLE
Will you support 1.10.2?

### ISSUE THREAD

**Issue by 5igm** [Mine-and-blade-admin/Battlegear2#233]
Although Minecraft has add the feature of holding stuffs by two hands in 1.9, it still can be improved such as in vanilla minecraft people cannot fight with two hands. They have to use one hand to hold the shield and the other is used to fight. Moreover, Battlegear2 has added some very interesting weapons which vanilla doesn't have. Thereby I am looking forward to the updated Battlegear2.

**Comment by GotoLink** [comment]
Yes. Thank you for your patience.
