### ISSUE TITLE
katana Kikoku

### ISSUE THREAD

**Issue by GokuSempai** [Mine-and-blade-admin/Battlegear2#236]
There' s a problem with the katana kikohu in the second hand (mod extra utilities) in the lastest version 1.7.10 
The katana is crooked and it makes ugly
It is a 3d modelisation katana 
![2016-11-17_15 59 12](https://cloud.githubusercontent.com/assets/22667528/20394185/f1a8adee-acde-11e6-8921-ed699c7db46b.png)

**Comment by GotoLink** [comment]
Most likely fixed in 1.11.
