### ISSUE TITLE
Use empty left hand (right click) crash

### ISSUE THREAD

**Issue by memoryman18** [Mine-and-blade-admin/Battlegear2#237]
When you have nothing in your left hand, clicking to use that for a punch will crash the game every time.

I know there's no real reason to use the off hand empty, but it is a crash that should be fixed for the quality of use. The first thing you do is try to punch things with both hands.

Heres the crash report in case it's unique to me however unlikely:

_---- Minecraft Crash Report ----

WARNING: coremods are present:
  Mine and Blade: Battlegear2 (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 24/11/16 22:45
Description: Unexpected error

java.lang.NoSuchFieldError: localPos
	at mods.battlegear2.BattlemodeHookContainerClass.copy(BattlemodeHookContainerClass.java:188)
	at mods.battlegear2.BattlemodeHookContainerClass.sendOffSwingEvent(BattlemodeHookContainerClass.java:229)
	at mods.battlegear2.BattlemodeHookContainerClass.playerInteract(BattlemodeHookContainerClass.java:146)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_BattlemodeHookContainerClass_playerInteract_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:123)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1489)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2036)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.battlegear2.BattlemodeHookContainerClass.copy(BattlemodeHookContainerClass.java:188)
	at mods.battlegear2.BattlemodeHookContainerClass.sendOffSwingEvent(BattlemodeHookContainerClass.java:229)
	at mods.battlegear2.BattlemodeHookContainerClass.playerInteract(BattlemodeHookContainerClass.java:146)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_16_BattlemodeHookContainerClass_playerInteract_PlayerInteractEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:123)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1489)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['SaltySamurai'/273, l='MpServer', x=-22.36, y=73.00, z=227.70]]
	Chunk stats: MultiplayerChunkCache: 619, 619
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 9.00,64.00,240.00 - World: (9,64,240), Chunk: (at 9,4,0 in 0,15; contains blocks 0,0,240 to 15,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9989 game time, 9989 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 65 total; [EntityZombie['Zombie'/132, l='MpServer', x=-30.50, y=43.00, z=174.03], EntityCreeper['Creeper'/133, l='MpServer', x=-21.50, y=29.00, z=188.50], EntitySkeleton['Skeleton'/134, l='MpServer', x=-26.13, y=46.00, z=188.41], EntitySheep['Sheep'/135, l='MpServer', x=-36.13, y=73.00, z=189.91], EntitySkeleton['Skeleton'/138, l='MpServer', x=-19.16, y=40.00, z=198.53], EntityCreeper['Creeper'/139, l='MpServer', x=-34.03, y=38.00, z=214.41], EntityZombie['Zombie'/140, l='MpServer', x=-30.50, y=29.00, z=224.50], EntitySquid['Squid'/141, l='MpServer', x=-27.35, y=60.00, z=251.82], EntitySheep['Sheep'/143, l='MpServer', x=-18.19, y=63.00, z=271.91], EntitySheep['Sheep'/144, l='MpServer', x=-18.13, y=63.00, z=269.81], EntitySheep['Sheep'/145, l='MpServer', x=-27.06, y=64.00, z=269.09], EntityBat['Bat'/1938, l='MpServer', x=47.35, y=51.32, z=185.35], EntitySkeleton['Skeleton'/1177, l='MpServer', x=-96.50, y=53.00, z=253.50], EntitySkeleton['Skeleton'/154, l='MpServer', x=-3.16, y=48.00, z=183.69], EntitySpider['Spider'/155, l='MpServer', x=-13.50, y=28.00, z=195.50], EntityCreeper['Creeper'/156, l='MpServer', x=-9.50, y=31.00, z=198.50], EntityEnderman['Enderman'/157, l='MpServer', x=-14.50, y=40.00, z=196.50], EntitySkeleton['Skeleton'/158, l='MpServer', x=-15.59, y=35.00, z=211.88], EntityCreeper['Creeper'/1957, l='MpServer', x=-57.50, y=13.00, z=252.50], EntityCreeper['Creeper'/170, l='MpServer', x=1.94, y=37.00, z=175.41], EntitySkeleton['Skeleton'/171, l='MpServer', x=6.50, y=14.00, z=200.50], EntityEnderman['Enderman'/172, l='MpServer', x=4.09, y=46.00, z=198.31], EntitySkeleton['Skeleton'/1324, l='MpServer', x=-31.50, y=61.00, z=246.50], EntityBat['Bat'/173, l='MpServer', x=1.08, y=16.19, z=229.71], EntitySquid['Squid'/174, l='MpServer', x=3.00, y=62.25, z=261.50], EntityPlayerSP['SaltySamurai'/273, l='MpServer', x=-22.36, y=73.00, z=227.70], EntitySkeleton['Skeleton'/176, l='MpServer', x=26.50, y=22.00, z=155.50], EntityCreeper['Creeper'/49, l='MpServer', x=-95.97, y=42.00, z=155.50], EntityPig['Pig'/177, l='MpServer', x=23.28, y=64.00, z=303.44], EntityPig['Pig'/178, l='MpServer', x=19.28, y=64.00, z=300.28], EntityPig['Pig'/179, l='MpServer', x=31.09, y=64.00, z=305.88], EntityZombie['Zombie'/1844, l='MpServer', x=-14.50, y=40.00, z=201.50], EntityPig['Pig'/180, l='MpServer', x=24.84, y=64.00, z=305.81], EntitySkeleton['Skeleton'/1466, l='MpServer', x=-14.50, y=40.00, z=195.50], EntitySheep['Sheep'/58, l='MpServer', x=-97.31, y=71.00, z=213.44], EntitySheep['Sheep'/59, l='MpServer', x=-97.25, y=72.00, z=208.25], EntitySheep['Sheep'/61, l='MpServer', x=-96.09, y=71.00, z=216.13], EntityCreeper['Creeper'/62, l='MpServer', x=-85.63, y=14.00, z=227.97], EntitySkeleton['Skeleton'/63, l='MpServer', x=-97.66, y=16.00, z=229.28], EntitySheep['Sheep'/192, l='MpServer', x=40.97, y=69.00, z=180.97], EntityCreeper['Creeper'/193, l='MpServer', x=32.50, y=12.00, z=202.50], EntityCreeper['Creeper'/66, l='MpServer', x=-98.50, y=53.00, z=248.50], EntityZombie['Zombie'/1480, l='MpServer', x=-84.66, y=37.00, z=148.34], EntityCreeper['Creeper'/76, l='MpServer', x=-87.47, y=38.00, z=157.06], EntityEnderman['Enderman'/78, l='MpServer', x=-92.50, y=42.00, z=176.50], EntityCreeper['Creeper'/79, l='MpServer', x=-91.50, y=40.00, z=191.50], EntitySheep['Sheep'/80, l='MpServer', x=-87.00, y=72.00, z=205.97], EntitySheep['Sheep'/81, l='MpServer', x=-94.09, y=72.00, z=210.16], EntityCreeper['Creeper'/1617, l='MpServer', x=48.50, y=50.00, z=181.50], EntitySheep['Sheep'/82, l='MpServer', x=-90.19, y=70.00, z=220.31], EntityCreeper['Creeper'/1875, l='MpServer', x=-73.55, y=61.00, z=179.26], EntitySkeleton['Skeleton'/214, l='MpServer', x=55.50, y=10.00, z=228.50], EntityCreeper['Creeper'/2014, l='MpServer', x=-43.50, y=42.00, z=231.50], EntitySkeleton['Skeleton'/95, l='MpServer', x=-64.84, y=30.00, z=149.50], EntityCreeper['Creeper'/1632, l='MpServer', x=-52.50, y=9.00, z=158.50], EntityZombie['Zombie'/97, l='MpServer', x=-69.53, y=36.00, z=155.94], EntityCreeper['Creeper'/99, l='MpServer', x=-67.50, y=48.00, z=152.50], EntityZombie['Zombie'/100, l='MpServer', x=-67.94, y=62.00, z=186.69], EntityBat['Bat'/1771, l='MpServer', x=-55.53, y=12.38, z=247.13], EntityCreeper['Creeper'/113, l='MpServer', x=-51.53, y=19.00, z=163.03], EntitySkeleton['Skeleton'/114, l='MpServer', x=-56.50, y=28.00, z=206.50], EntityBat['Bat'/1659, l='MpServer', x=-19.54, y=31.83, z=198.63], EntitySpider['Spider'/124, l='MpServer', x=-37.03, y=47.00, z=185.28], EntityCreeper['Creeper'/125, l='MpServer', x=-38.50, y=48.00, z=181.97], EntityBat['Bat'/127, l='MpServer', x=-35.40, y=22.10, z=207.30]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 259818424 bytes (247 MB) / 632410112 bytes (603 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1722 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	Forge{11.15.1.1722} [Minecraft Forge] (forge-1.8.9-11.15.1.1722.jar) 
	UCHIJAAAA	battlegear2{1.8.9} [Mine & Blade Battlegear 2 - Bullseye] (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar) 
	Loaded coremods (and transformers): 
Mine and Blade: Battlegear2 (1.8.9-MB_Battlegear2-Bullseye-1.0.10.2.jar)
  mods.battlegear2.coremod.transformers.EntityPlayerTransformer
  mods.battlegear2.coremod.transformers.ModelBipedTransformer
  mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
  mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
  mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
  mods.battlegear2.coremod.transformers.ItemRendererTransformer
  mods.battlegear2.coremod.transformers.RenderItemTransformer
  mods.battlegear2.coremod.transformers.MinecraftTransformer
  mods.battlegear2.coremod.transformers.ItemStackTransformer
  mods.battlegear2.coremod.transformers.ItemInWorldTransformer
  mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
  mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.90' Renderer: 'GeForce GTX 690/PCIe/SSE2'
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1722
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 690/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.90, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz_

**Comment by GotoLink** [comment]
Find an older version of Forge.
They broke compatibility and i am more concerned about Minecraft 1.10 at the moment.
