### ISSUE TITLE
[1.7.10] I have a problem with 2 arms.

### ISSUE THREAD

**Issue by demycat** [Mine-and-blade-admin/Battlegear2#244]
When I turn on two hands (in both swords), but when I press right click, he does not beat, but defended himself(but left click is working fine)
How fix it?
![2018-03-18_12 35 35](https://user-images.githubusercontent.com/34833284/37564985-79bbdae6-2aa9-11e8-86dd-3a0df8121320.png)
![2018-03-18_12 35 39](https://user-images.githubusercontent.com/34833284/37564986-79dbdcce-2aa9-11e8-9327-e4aa2d033805.png)
![2018-03-18_12 39 45](https://user-images.githubusercontent.com/34833284/37564987-79fb246c-2aa9-11e8-9163-8825b8ef0ac9.png)

**Comment by destructor121234** [comment]
I am experiencing the exact same problem with my mod in 1.7.10. Someone please tell me how to fix it!!

**Comment by GotoLink** [comment]
No enemy in front of you ? 
No attack.
